#!/usr/bin/env ruby

require 'gmail'
require 'ap'
require 'mc-settings'

class GmailMonitor
	def initialize( mailboxes_to_monitor, email_address_to_monitor, password )
		@mailboxes = mailboxes_to_monitor
		@login		 = email_address_to_monitor
		@password  = password
	end

	def monitor
    Gmail.new(@login, @password) do |gmail|
      stats = {}
    	@mailboxes.each do |mailbox|
    	  info = monitor_mailbox gmail, mailbox
        stats.merge! info if ! info.nil?
    	end

      ap stats
    end
	end

	def monitor_mailbox( gmail, name )
    # puts "Looking up folder >#{name}<"
    mail_box 	= gmail.label( name )
    count			= mail_box.count :unread

    return if count <= 0

    # print_mailbox_count name, count
    # print_unread_subjects mail_box
    { name => count }
	end

  def print_mailbox_count( name, count )
    puts "#{name}: #{count}" if count > 0
  end

	def print_unread_subjects( mail_box )
  	mail_box.emails( :unread ).each do |email|
  	  puts "    #{email.subject}"
  	  email.mark :unread
  	end
	end
end

# rc_file = "#{ENV['HOME']}/.gmailnrc"
# puts "Reading rc file >#{rc_file}<"

# rails ArgumentError( "You must have a ~/.gmailnrc file defining folders, email, and login." ) if ! File.exists? rc_file

# load rc_file

Setting.load( :path  => "#{ENV['HOME']}/.config/gmailn",
              :files => [ "default.yml" ],
              :local => true )

# ap Setting.email
# ap Setting.folders

GmailMonitor.new( Setting.folders, Setting.email, Setting.password ).monitor
